name: cd

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          push: true
          tags: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: 'ghcr.io'
          repository: 'idoneam/minicrossword-bot'
      - uses: './.github/actions/redeploy'
        with:
          key: ${{ secrets.VM_KEY }}
          ip: ${{ secrets.VM_IP }}
          pub_host: ${{ secrets.VM_PUB_HOST }}
          user: ${{ secrets.VM_USER }}
          dir: 'minicross'
          name: 'minicrossword-bot'
          image: 'ghcr.io/idoneam/minicrossword:latest'
          dr_args: '--env-file=$(pwd)/.env restart=always -v $(pwd)/Scoreboard.db:/bot/Scoreboard.db'
